### ISSUE TITLE
clarify feature difference of collection links and main search

### ISSUE THREAD

**Issue by Chovin** [OIT-UOG/specify-webportal-installer#39]
Was just thinking...do you guys think we need to include a brief statement on the front page that clarifies that users can use the quick search box or click on the collection icons below for more advanced queries? This would be in lieu of the "Select a collection below" statement, which is ambiguous now that there are two ways to query the different databases

_Originally posted by @burdickdr in https://github.com/OIT-UOG/specify-webportal-installer/issues/21#issuecomment-481902578_

**Comment by burdickdr** [comment]
Looks good!
